# use gpg key instead of an ssh key
if [ -f "${HOME}/.gpg-agent-info" ]; then
	source "${HOME}/.gpg-agent-info"
	export GPG_AGENT_INFO
	export SSH_AUTH_SOCK
	export SSH_AGENT_PID
else
	eval $( gpg-agent --daemon --write-env-file ~/.gpg-agent-info )
fi

if [ -z "$DISPLAY" ] && [ $(tty) == /dev/tty1 ]; then
	startx
fi
